version: '3'

services:
    postgres:
        container_name: rblf-selecao-gersist-db
        image: postgres
        ports:
            - 5432:5432
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_URL=${DATABASE_URL}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: